name: CI - Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint
        run: |
          python -m pip install flake8
          flake8 --max-line-length=120 || true

      - name: Simple smoke test (start app)
        run: |
          nohup python app.py &
          sleep 5
          curl -sSf http://127.0.0.1:5000
